### ISSUE TITLE
Error in file(con, "w") 

### ISSUE THREAD

**Issue by focuslyj** [CSkylarL/TimiGP#2]
When running:res <- TimiPermFDR(resdata = res, geneset = geneset, gene = GP,
                   background = background, niter = 100, core = 20)

Report an error:--------------- Run 100 permutations. Please be patient ---------------
Permeutation#1: Different / Total markers: 544/545
Permeutation#2: Different / Total markers: 543/545
Error in file(con, "w") : 所有链结都已在运行

**Comment by CSkylarL** [comment]
Could you please clarify the error in English? Thanks!

**Comment by focuslyj** [comment]
Professor, I'm sorry.
        R version 4.2.2.  the environment win11
When running:res <- TimiPermFDR(resdata = res, geneset = geneset, gene = GP,
background = background, niter = 100, core = 20)

Report an error:--------------- Run 100 permutations. Please be patient ---------------
Permeutation#1: Different / Total markers: 544/545
Permeutation#2: Different / Total markers: 543/545
Error in file(con, "w") : all connections are in run
I initially think it may be the problem of environmental variables.
                                                                               thanks！

**Comment by CSkylarL** [comment]
Thanks for clarifying the error message. 
It looks like R parallel errors. Your hardware or R environment may not support the `core = 20`. Could you please try the below code? I set the `core = 1` to reduce the computational requirement and `niter=10` to quickly check the code. 

```R
res <- TimiPermFDR(resdata = res, geneset = geneset, gene = GP,
                   background = background, niter = 10, core = 1)
```
If the code works, please set the `niter = 100` and try to reduce the number of cores used in your analysis (e.g. `core = 3` or `core = 5`).

Thanks for using TimiGP,
Skylar

**Comment by focuslyj** [comment]
thanks！
